import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { User } from 'lucide-react';
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div lang="en">
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-blue-800 flex justify-between items-center h-24 relative">
          
          <div className="absolute left-1/2 transform -translate-x-1/2">
              <Link href="/">
                <Image
                  src="/logor3.png"
                  alt="Logo"
                  width={70}
                  height={70}
                />
              </Link>
          </div>

          <div className="ml-auto mr-4">
            <div className="list-none gap-2 flex">
              <div>
                <Link
                  href="/login"
                  className="custom-class text-white text-xl bg-blue-800 hover:bg-blue-700 hover:text-white"
                >
                  <User className="inline-block h-6 w-6 mr-2" />
                  Login para Administrador
                </Link>
              </div>
            </div>
          </div>
        </div>
        {children}
      </div>
    </div>    
  );
}
